const params=new URLSearchParams(location.search);const roomId=params.get("room");const liveStage=document.querySelector(".live-stage"),roomStatus=document.getElementById("roomStatus"),viewerCount=document.getElementById("viewerCount"),sideViewerCount=document.getElementById("sideViewerCount"),reactionCount=document.getElementById("reactionCount"),chatList=document.getElementById("chatList"),chatForm=document.getElementById("chatForm"),chatInput=document.getElementById("chatInput"),endLiveBtn=document.getElementById("endLiveBtn"),roomTitle=document.getElementById("roomTitle"),roomHeading=document.getElementById("roomHeading"),roomCreator=document.getElementById("roomCreator"),creatorName=document.getElementById("creatorName"),liveRoomStatus=document.getElementById("liveRoomStatus"),reactionFloat=document.getElementById("reactionFloat");let user=null,room=null,channel=null;
(async()=>{user=await BeyondAuth.getCurrentUser();if(!user){location.href="login.html?next="+encodeURIComponent(location.pathname+location.search);return}if(roomId) await joinExistingRoom();else await startRoom();})();
async function startRoom(){const title=prompt("Give your live stream a title","Beyond Live")?.trim()||"Beyond Live";const {data,error}=await supabaseClient.from("live_rooms").insert({creator_id:user.id,title,status:"live"}).select().single();if(error){liveRoomStatus.textContent=error.message||"Could not start live room.";return}history.replaceState(null,"","live-room.html?room="+data.id);room=data;endLiveBtn.hidden=false;await setupRoom()}
async function joinExistingRoom(){const {data,error}=await supabaseClient.from("live_rooms").select("id,creator_id,title,status,started_at").eq("id",roomId).maybeSingle();if(error||!data){liveRoomStatus.textContent="Live room not found.";return}room=data;if(room.status!=="live"){roomStatus.textContent="ENDED";liveRoomStatus.textContent="This live stream has ended.";chatForm.querySelector("button").disabled=true;chatInput.disabled=true;return}await supabaseClient.from("live_viewers").upsert({room_id:room.id,user_id:user.id,last_seen_at:new Date().toISOString()});await setupRoom()}
async function setupRoom(){roomTitle.textContent=room.title;roomHeading.textContent=room.title;const {data:p}=await supabaseClient.from("profiles").select("username,display_name").eq("id",room.creator_id).maybeSingle();const name=p?.display_name||"Beyond Creator";roomCreator.textContent="@"+(p?.username||"creator");creatorName.textContent=name;if(room.creator_id===user.id)endLiveBtn.hidden=false;await loadChat();await refreshStats();subscribeRealtime();setInterval(heartbeat,20000)}
async function heartbeat(){if(!room||!user)return;await supabaseClient.from("live_viewers").upsert({room_id:room.id,user_id:user.id,last_seen_at:new Date().toISOString()})}
async function refreshStats(){const cutoff=new Date(Date.now()-45000).toISOString();const {data:viewers=[]}=await supabaseClient.from("live_viewers").select("user_id").eq("room_id",room.id).gte("last_seen_at",cutoff);const {count:reactions}=await supabaseClient.from("live_reactions").select("*",{count:"exact",head:true}).eq("room_id",room.id);viewerCount.textContent=viewers.length;sideViewerCount.textContent=viewers.length;reactionCount.textContent=reactions||0}
async function loadChat(){const {data,error}=await supabaseClient.from("live_chat_messages").select("id,user_id,message,created_at").eq("room_id",room.id).order("created_at",{ascending:true}).limit(100);if(error){liveRoomStatus.textContent="Run live-room.sql in Supabase first.";return}chatList.replaceChildren();for(const item of data||[])addChat(item)}
async function addChat(item){const row=document.createElement("article");row.className="live-chat-message";row.dataset.chatId=item.id;row.innerHTML='<strong>Beyond user</strong><p>'+escapeHTML(item.message)+'</p>';const {data:p}=await supabaseClient.from("profiles").select("username,display_name").eq("id",item.user_id).maybeSingle();if(p)row.querySelector("strong").textContent=p.display_name||("@"+p.username);chatList.appendChild(row);chatList.scrollTop=chatList.scrollHeight}
chatForm.addEventListener("submit",async e=>{e.preventDefault();const message=chatInput.value.trim();if(!message||!room)return;chatInput.value="";const {error}=await supabaseClient.from("live_chat_messages").insert({room_id:room.id,user_id:user.id,message});if(error){chatInput.value=message;liveRoomStatus.textContent=error.message||"Could not send message.";}});
document.querySelectorAll(".reaction-buttons button").forEach(btn=>btn.addEventListener("click",async()=>{if(!room)return;const reaction=btn.dataset.reaction;const {error}=await supabaseClient.from("live_reactions").insert({room_id:room.id,user_id:user.id,reaction});if(error){liveRoomStatus.textContent=error.message||"Could not send reaction.";return}showReaction(btn.textContent)}));
function showReaction(value){reactionFloat.textContent=value;reactionFloat.classList.remove("pop");void reactionFloat.offsetWidth;reactionFloat.classList.add("pop")}
endLiveBtn.addEventListener("click",async()=>{if(!room||room.creator_id!==user.id)return;if(!confirm("End this Beyond Live?"))return;const {error}=await supabaseClient.from("live_rooms").update({status:"ended",ended_at:new Date().toISOString()}).eq("id",room.id).eq("creator_id",user.id);if(error){liveRoomStatus.textContent=error.message;return}roomStatus.textContent="ENDED";endLiveBtn.disabled=true;liveRoomStatus.textContent="Live stream ended.";if(channel)await supabaseClient.removeChannel(channel)});
function subscribeRealtime(){channel=supabaseClient.channel("live-room-"+room.id).on("postgres_changes",{event:"*",schema:"public",table:"live_chat_messages",filter:"room_id=eq."+room.id},payload=>{if(payload.eventType==="INSERT"&&!document.querySelector(`[data-chat-id="${payload.new.id}"]`))addChat(payload.new)}).on("postgres_changes",{event:"*",schema:"public",table:"live_reactions",filter:"room_id=eq."+room.id},payload=>{if(payload.eventType==="INSERT"){reactionCount.textContent=Number(reactionCount.textContent||0)+1;showReaction(payload.new.reaction==="love"?"❤️":payload.new.reaction==="fire"?"🔥":payload.new.reaction==="wow"?"😮":"👍")}}).on("postgres_changes",{event:"*",schema:"public",table:"live_viewers",filter:"room_id=eq."+room.id},()=>refreshStats()).on("postgres_changes",{event:"*",schema:"public",table:"live_rooms",filter:"id=eq."+room.id},payload=>{if(payload.new?.status==="ended"){roomStatus.textContent="ENDED";liveRoomStatus.textContent="This live stream has ended."}}).subscribe()}
function escapeHTML(value=""){const d=document.createElement("div");d.textContent=value;return d.innerHTML}window.addEventListener("beforeunload",async()=>{if(room&&user)await supabaseClient.from("live_viewers").delete().eq("room_id",room.id).eq("user_id",user.id);if(channel)await supabaseClient.removeChannel(channel)});